name: Automatic Rebase
on:
  issue_comment:
    types: [created]

permissions:
  contents: read
  pull-requests: write
  issues: read
  # Enforce other not needed permissions are off
  actions: none
  checks: none
  deployments: none
  packages: none
  repository-projects: none
  security-events: none
  statuses: none

jobs:
  rebase:
    name: Rebase
    if: github.event.comment.author_association == 'COLLABORATOR' && github.event.issue.pull_request != '' && contains(github.event.comment.body, '/rebase')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the latest code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0 # otherwise, you will fail to push refs to dest repo
      - name: Automatic Rebase
        uses: cirrus-actions/rebase@1.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
