name: Build alpha release for Docker Hub

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Docker tag'
        required: true

jobs:
  build:
    name: Run Gitian build
    runs-on: self-hosted
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build depends
      run: |
        cd depends
        make -j2
        cd ..
